# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/ui/connect_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConnectDialog(object):
    def setupUi(self, ConnectDialog):
        ConnectDialog.setObjectName("ConnectDialog")
        ConnectDialog.resize(551, 202)
        self.gridLayout_2 = QtWidgets.QGridLayout(ConnectDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.url_label = QtWidgets.QLabel(ConnectDialog)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.url_label.sizePolicy().hasHeightForWidth()
        )
        self.url_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        self.url_label.setFont(font)
        self.url_label.setLocale(
            QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates)
        )
        self.url_label.setObjectName("url_label")
        self.verticalLayout.addWidget(self.url_label)
        self.url_edit = QtWidgets.QLineEdit(ConnectDialog)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.url_edit.sizePolicy().hasHeightForWidth()
        )
        self.url_edit.setSizePolicy(sizePolicy)
        self.url_edit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.url_edit.setLocale(
            QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates)
        )
        self.url_edit.setObjectName("url_edit")
        self.verticalLayout.addWidget(self.url_edit)
        self.name_label = QtWidgets.QLabel(ConnectDialog)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.name_label.sizePolicy().hasHeightForWidth()
        )
        self.name_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        self.name_label.setFont(font)
        self.name_label.setLocale(
            QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates)
        )
        self.name_label.setObjectName("name_label")
        self.verticalLayout.addWidget(self.name_label)
        self.conn_name_edit = QtWidgets.QLineEdit(ConnectDialog)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.conn_name_edit.sizePolicy().hasHeightForWidth()
        )
        self.conn_name_edit.setSizePolicy(sizePolicy)
        self.conn_name_edit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.conn_name_edit.setLocale(
            QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates)
        )
        self.conn_name_edit.setObjectName("conn_name_edit")
        self.verticalLayout.addWidget(self.conn_name_edit)
        self.connect_button = QtWidgets.QPushButton(ConnectDialog)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.connect_button.sizePolicy().hasHeightForWidth()
        )
        self.connect_button.setSizePolicy(sizePolicy)
        self.connect_button.setObjectName("connect_button")
        self.verticalLayout.addWidget(self.connect_button)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.name_label_2 = QtWidgets.QLabel(ConnectDialog)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.name_label_2.sizePolicy().hasHeightForWidth()
        )
        self.name_label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        self.name_label_2.setFont(font)
        self.name_label_2.setLocale(
            QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates)
        )
        self.name_label_2.setObjectName("name_label_2")
        self.verticalLayout_2.addWidget(self.name_label_2)
        self.server_selector = QtWidgets.QComboBox(ConnectDialog)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.server_selector.sizePolicy().hasHeightForWidth()
        )
        self.server_selector.setSizePolicy(sizePolicy)
        self.server_selector.setLocale(
            QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates)
        )
        self.server_selector.setObjectName("server_selector")
        self.verticalLayout_2.addWidget(self.server_selector)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 3, 0, 1, 1)
        self.line = QtWidgets.QFrame(ConnectDialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 1, 0, 2, 2)

        self.retranslateUi(ConnectDialog)
        QtCore.QMetaObject.connectSlotsByName(ConnectDialog)

    def retranslateUi(self, ConnectDialog):
        _translate = QtCore.QCoreApplication.translate
        ConnectDialog.setWindowTitle(
            _translate("ConnectDialog", "New openEO Connection")
        )
        self.url_label.setText(_translate("ConnectDialog", "URL"))
        self.name_label.setText(_translate("ConnectDialog", "Name"))
        self.connect_button.setText(
            _translate("ConnectDialog", "Create Connection")
        )
        self.name_label_2.setText(
            _translate("ConnectDialog", "Select Server from openEO Hub")
        )
