# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/ui/connect_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

"""
This file is a result of `pb_tool compile`.
"""


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SpatialDialog(object):
    def setupUi(self, SpatialDialog):
        SpatialDialog.setObjectName("SpatialDialog")
        SpatialDialog.resize(532, 193)
        self.gridLayout_2 = QtWidgets.QGridLayout(SpatialDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.name_label_2 = QtWidgets.QLabel(SpatialDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.name_label_2.setFont(font)
        self.name_label_2.setObjectName("name_label_2")
        self.gridLayout_2.addWidget(self.name_label_2, 3, 0, 1, 1)
        self.server_selector = QtWidgets.QComboBox(SpatialDialog)
        self.server_selector.setObjectName("server_selector")
        self.gridLayout_2.addWidget(self.server_selector, 4, 0, 1, 2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.url_label = QtWidgets.QLabel(SpatialDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.url_label.setFont(font)
        self.url_label.setObjectName("url_label")
        self.verticalLayout.addWidget(self.url_label)
        self.url_edit = QtWidgets.QLineEdit(SpatialDialog)
        self.url_edit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.url_edit.setObjectName("url_edit")
        self.verticalLayout.addWidget(self.url_edit)
        self.name_label = QtWidgets.QLabel(SpatialDialog)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.name_label.setFont(font)
        self.name_label.setObjectName("name_label")
        self.verticalLayout.addWidget(self.name_label)
        self.conn_name_edit = QtWidgets.QLineEdit(SpatialDialog)
        self.conn_name_edit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.conn_name_edit.setObjectName("conn_name_edit")
        self.verticalLayout.addWidget(self.conn_name_edit)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.logo = QtWidgets.QLabel(SpatialDialog)
        self.logo.setMaximumSize(QtCore.QSize(100, 75))
        self.logo.setWhatsThis("")
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("gui/ui/../images/icon_large.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.verticalLayout_3.addWidget(self.logo)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.connect_button = QtWidgets.QPushButton(SpatialDialog)
        self.connect_button.setObjectName("connect_button")
        self.verticalLayout_3.addWidget(self.connect_button)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 0, 1, 1, 1)
        self.line = QtWidgets.QFrame(SpatialDialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 1, 0, 2, 2)

        self.retranslateUi(SpatialDialog)
        QtCore.QMetaObject.connectSlotsByName(SpatialDialog)

    def retranslateUi(self, SpatialDialog):
        _translate = QtCore.QCoreApplication.translate
        SpatialDialog.setWindowTitle(_translate("SpatialDialog", "openEO Connector"))
        self.name_label_2.setText(_translate("SpatialDialog", "Select server"))
        self.url_label.setText(_translate("SpatialDialog", "Connection URL"))
        self.name_label.setText(_translate("SpatialDialog", "Connection Name"))
        self.connect_button.setText(_translate("SpatialDialog", "create connection"))
