# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui/ui/login_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SpatialDialog(object):
    def setupUi(self, SpatialDialog):
        SpatialDialog.setObjectName("SpatialDialog")
        SpatialDialog.resize(551, 285)
        self.gridLayout_2 = QtWidgets.QGridLayout(SpatialDialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(SpatialDialog)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.internal = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.internal.sizePolicy().hasHeightForWidth())
        self.internal.setSizePolicy(sizePolicy)
        self.internal.setMaximumSize(QtCore.QSize(523, 16777215))
        self.internal.setObjectName("internal")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.internal)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.usernameLabel = QtWidgets.QLabel(self.internal)
        self.usernameLabel.setObjectName("usernameLabel")
        self.verticalLayout_3.addWidget(self.usernameLabel)
        self.usernameEdit = QtWidgets.QLineEdit(self.internal)
        self.usernameEdit.setObjectName("usernameEdit")
        self.verticalLayout_3.addWidget(self.usernameEdit)
        self.passwordLabel = QtWidgets.QLabel(self.internal)
        self.passwordLabel.setObjectName("passwordLabel")
        self.verticalLayout_3.addWidget(self.passwordLabel)
        self.passwordEdit = QtWidgets.QLineEdit(self.internal)
        self.passwordEdit.setObjectName("passwordEdit")
        self.verticalLayout_3.addWidget(self.passwordEdit)
        self.description = QtWidgets.QLabel(self.internal)
        self.description.setObjectName("description")
        self.verticalLayout_3.addWidget(self.description)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.authButton = QtWidgets.QPushButton(self.internal)
        self.authButton.setObjectName("authButton")
        self.verticalLayout_3.addWidget(self.authButton)
        self.tabWidget.addTab(self.internal, "")
        self.gridLayout_2.addWidget(self.tabWidget, 9, 0, 1, 1)
        self.titleLabel = QtWidgets.QLabel(SpatialDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleLabel.sizePolicy().hasHeightForWidth())
        self.titleLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        self.titleLabel.setFont(font)
        self.titleLabel.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.titleLabel.setObjectName("titleLabel")
        self.gridLayout_2.addWidget(self.titleLabel, 0, 0, 1, 1)

        self.retranslateUi(SpatialDialog)
        QtCore.QMetaObject.connectSlotsByName(SpatialDialog)

    def retranslateUi(self, SpatialDialog):
        _translate = QtCore.QCoreApplication.translate
        SpatialDialog.setWindowTitle(_translate("SpatialDialog", "Authenticate connection"))
        self.usernameLabel.setText(_translate("SpatialDialog", "Username"))
        self.passwordLabel.setText(_translate("SpatialDialog", "Password"))
        self.description.setText(_translate("SpatialDialog", "<html><head/><body><p><span style=\" font-weight:700; color:#c01c28;\">warning: </span><span style=\" color:#000000;\">credentials are stored as plain text in project file</span></p></body></html>"))
        self.authButton.setText(_translate("SpatialDialog", "Authenticate with internal log in"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.internal), _translate("SpatialDialog", "Internal"))
        self.titleLabel.setText(_translate("SpatialDialog", "Log in to"))
